### ISSUE TITLE
[QUESTION 🤔] Newer versions contain less features (no fps, no return converted frame)

### ISSUE THREAD

**Issue by mikoprus** [luicfrr/react-native-vision-camera-face-detector#51]
Older versions (1.3.4) allowed for implementation where we could use detectFaces with runAtFps function, it's not possible in 1.6.1.
1.3.4 allowed to return converted frame in base64 string and it's missing in 1.6.1 as well

**Comment by nonam4** [comment]
You can still use `detectFaces` with `runAtFps`. I'll readd this example on README's file but you can use [Camera.tsx](https://github.com/nonam4/react-native-vision-camera-face-detector/blob/3f2008f75be8170645b2d71f8aca45790906950b/src/Camera.tsx) file as example. I'll leave this issue open while I don't do this.

About base64 conversion this feature makes no sense on this package because it's for face detection not for frame conversion so I dropped it's support.

If you need this feature maybe you should create your own frame conversion plugin (or you can pay me to create it for you). 
If you want to create it yourself you can use this repo as base for it and you can find removed conversion code in 337d131 commit but this is all the help I can give you without any payment.
